openapi: 3.0.0
info:
  title: API Backend Ecommerce - Carrito
  version: 1.0.0
  description: Documentación de la API para el manejo de carrito de compras

paths:

  /carrito/:cid:  
    get:
      summary: Buscar el carrito de compras por id y renderizarlo en la vista carrito.handlebars
      tags:
        - Carrito
      description: Renderiza la vista de carrito con los productos que contiene el mismo.
      parameters:
        - in: path
          name: cid  
          schema:
            type: string
          required: true
          description: El ID del carrito que se desea renderizar.
      responses:
        '200':
          description: Éxito. Página de inicio renderizada correctamente con los productos de la base de datos.
          content:
            text/html:
              schema: 
                $ref: '#/components/schemas/Cart' 
              example: |
                {{>menu}}
                <h1>Carrito de compras</h1>
                {{#if carts.items.length}}
                  <ul>
                    {{#each carts.items}}
                      <li>
                        <img src="{{this.product.thumbnails.[0]}}" alt="{{this.product.title}}"> 
                        <h2>{{this.product.title}}</h2>
                        <p>Descripción: {{this.product.description}}</p>
                        <p>Precio: {{this.product.price}}</p>
                        <p>Categoría: {{this.product.category}}</p>
                        <p>Cantidad: {{this.quantity}}</p>
                        <button onclick="eliminarProducto('{{this.product._id}}','{{usuario.carrito}}')">Eliminar del carrito</button>
                      </li>
                    {{/each}}
                    <h3>Total: {{totalCartPrice}} </h3>
                    <button onclick="realizarCompra('{{usuario.carrito}}')">Comprar</button>
                  </ul>
                {{else}}
                  <p>El carrito está vacío.</p>
                {{/if}}

                <br>

                <script>
                  // Funciones JavaScript
                </script>
        '404':
          description: Error al encontrar el carrito, no existe el carrito de compras.
          content:
            application/json:
              schema: 
                type: object
                properties:
                  error:
                    type: string
                    description: Mensaje de error. No se encontró el carrito.
              example:
                error: No se ha encontrado el carrito específico.
        '400':
          description: Error. Se debe proporcionar un ID de carrito válido.
          content:
            application/json:
              schema: 
                type: object
                properties:
                  error:
                    type: string
                    description: Error el id del carrito no es válido.
              example:
                error: El ID del carrito proporcionado no es válido.

components:
  schemas:
    CartItem:
      type: object
      properties:
        product:
          type: string
          description: ID del producto en el carrito.
        quantity:
          type: integer
          description: Cantidad del producto en el carrito.
      required:
        - product
        - quantity

    Cart:
      type: object
      properties:
        items:
          type: array
          description: Elementos en el carrito.
          items:
            $ref: '#/components/schemas/CartItem'
      required:
        - items

 